### ISSUE TITLE
Mass Effect 2 cannot be launched through Origin with modified dll

### ISSUE THREAD

**Issue by HylianSteel** [Erik-JS/masseffect-binkw32#11]
I can't launch Mass Effect 2 through Origin with the modified .dll in place. I also can't launch Mass Effect 2 from the shortcuts placed on my desktop and in my start menu. I think that Origin uses MassEffect2.exe to launch the game and that's what the shortcuts point to as well, but as we know, the game's real exe is ME2Game.exe. Could you take a look at it?

**Comment by Erik-JS** [comment]
As I said in #10, I can't do anything else besides checking the game on my own (real) machines. And the game is still working here.

Have you checked the Documents folder? (binkw32-me2.log)

Which mods are you using? For the record, I don't use any ME2 mods here, and I cannot guarantee that this will work with all ME2 mods.

**Comment by HylianSteel** [comment]
My binkw32-me2.log: 

ME2 Autopatcher by Erik JS
Based on original code by Warranty Voider
Addresses loaded from binkw23.dll - OK
Console patch: done
DLC check - position: 0x9584CB
DLC check - patch: done

I do have ALOT installed through the use of MassEffectModder. I'm going to vanilla the game and check to see if it'll launch MassEffect2.exe with your dlls.

**Comment by Erik-JS** [comment]
From the log, binkw32 is "working as intended". Waiting for vanilla results...

**Comment by HylianSteel** [comment]
Results are back. MassEffectModder (and ALOT by extension I guess) is changing the game in such a way that prevents it from launching through origin and MassEffect2.exe with your dll... and also the vanilla dll. My apologies for wasting your time. I'll go report this to the right people.
