### ISSUE TITLE
Documentation: Should specify do not have 2 same-named ASI's in me3.exe folder and asi/ subfolder

### ISSUE THREAD

**Issue by Mgamerz** [Erik-JS/masseffect-binkw32#12]
Was testing out some mod manager code and found a unique crash situation which can arise if you have the same ASI (unsure if code or just filenames) in both the win32 directory and the asi/ subdirectory. My game would not start up and it took me some time to figure out why - the way mod manager works this won't occur (as long as the user doesn't do anything on their own), but it was an interesting issue to run into while testing importing same file source/destination code.

(Mod Manager exclusively works in /asi)

**Comment by Erik-JS** [comment]
Noted. I'll check this out later and see what I can do about it.

**Comment by Mgamerz** [comment]
Cool, thanks :)

**Comment by Erik-JS** [comment]
OK, so I tried to "duplicate" some plugins, and there was either some error properly caught on the log, or the plugin presented some abnormal behavior. Even though I had no crashes here, this issue you brought up still stands. For instance, loading two ASI plugins with the same name and from different places can cause some trouble (or confusion, at least) when using something like GetModuleHandle("xxx.asi").

Currently, the ASI loader works like this:
1) search for and load any plugins in the current folder (win32);
2) search for and load any plugins in the asi subfolder, regardless of what has been already loaded in the previous step.

This is what I'll implement:
1) search for and load any plugins in the asi subfolder;
2) if nothing was loaded from there, search for and load any plugins in the current folder (win32).

This issue will be closed once a proper fix is publicly available, through a new release for this repository.
