### ISSUE TITLE
Visual C++ 2015 is not required if 2017 is installed (and will fail to install)

### ISSUE THREAD

**Issue by Mgamerz** [Erik-JS/masseffect-binkw32#13]
Updating my binkw32 version in mod manager,  Found another nice issue. It seems Visual C++ 2017 is a binary compatible upgrade to 2015 and will block installation of 2015 if it is installed.

https://developercommunity.visualstudio.com/content/problem/14701/visual-c-redistributable-for-visual-studio-2015-ca.html

I am learning that is big PITA to detect these versions and I have no idea how to maintain forwards compatibility by detecting it. Just a heads up, the links you provided for installation may or may not work if a user has a newer version already installed.

Additionally, I uninstalled my all VC++ versions above 2013 and the game is still able to load - are you sure these require 2015?

**Comment by Mgamerz** [comment]
Update: It seems my working environment makes it so that VC2015+ is installed somehow even if it is not in my list of installed programs. I tested on another machine (with no microsoft dev tools installed) and installing VC2015 or VC2017 allowed the bink to work, otherwise I would get the license error page.

So VC2015 and VC2017 works, and your tool does (as expected) require one of them.

**Comment by Erik-JS** [comment]
Just for the record, I found these links through Google. The explanation on why 2015 and 2017 are binary compatible:

https://stackoverflow.com/questions/44288837/binary-compatibility-between-vs2017-and-vs2015
https://www.reddit.com/r/cpp/comments/6gshou/vs2017vc141_is_binary_compatible_with_vs2015vc140/
