### ISSUE TITLE
Issues with DLC Patch

### ISSUE THREAD

**Issue by starkgate** [Erik-JS/masseffect-binkw32#14]
I've received a report from a user of my ME2 mod (ALOT), saying that the new version of your DLC patch isn't working (see screenshot below). I had them use the previous version (v2) instead, which fixed the problem. I couldn't reproduce the issue myself, loading either DLL works on my vanilla ME2.

Any idea what could be the cause of this ?
http://prntscr.com/fylela

**Comment by Mgamerz** [comment]
I'm on the same discord and we checked and verified he has VC2015 x86 installed as well.

I am not sure if it is possible but can you build against only a specific subversion of VC? I know they made an update 3 version.

**Comment by Mgamerz** [comment]
User installed VC 2017 and it seems to have worked - does it not work with 2015?

**Comment by Erik-JS** [comment]
While I'm correctly telling that I used VS 2015 Update 3 in the readme.txt files, the link for redistributable in those files and the main repo readme is technically "outdated". The actual _minimum_ requirement is this:
https://www.microsoft.com/en-us/download/details.aspx?id=53587

I don't know why I didn't notice this earlier. I'll run some tests here and update all readme's later.

**Comment by Mgamerz** [comment]
Should you just point it to VC 2017 as it is compatible?

**Comment by Erik-JS** [comment]
Additional VC runtime install (2015/2017) is no longer required as of [r4](https://github.com/Erik-JS/masseffect-binkw32/releases/tag/r4). I'm closing this issue now.

**Comment by starkgate** [comment]
Thank you !
