### ISSUE TITLE
Write logs in the games log folder

### ISSUE THREAD

**Issue by mirh** [Erik-JS/masseffect-binkw32#16]
I understand #8, but writing in the documents folder sounds like having chosen the first path that came to one's mind. 
All three ME games have a dedicated log directory inside their config/saves ones, so why not using that?

**Comment by Erik-JS** [comment]
For a successful log file creation, the binkw32 patch needs a folder whose existence is *always* guaranteed before the game is run. The likelihood of `%userprofile%\Documents` not existing is way lower than `%userprofile%\Documents\BioWare\Mass Effect [2/3] `. The goal here is to be able to have a log file even if it's the very first time the user is running the game.

**Comment by mirh** [comment]
Putting aside that I don't see why you couldn't try to create it, why don't you just add it higher in the "priority" list (which I'd argue should have the game folder on top tbh)?

**Comment by Mgamerz** [comment]
This is an open source project. If you want that implemented you can fork
the repo and create it yourself. I don't think there is any pressing need
for a feature such as this given there has been no requests or issues of
this kind for years

**Comment by mirh** [comment]
There is no pressing need, yes. I'm fine with that.

**Comment by Erik-JS** [comment]
In absence of further discussion, I'm closing this issue. I appreciate your suggestion but right now I don't see any technical reason to change the path where the log file is being created. About binkw32 creating the game folder if it doesn't exist.... well... I say let the game handle its own folder in this case.

As already pointed by @Mgamerz, forking the repo and making personal tweaks is and always will be an option here.

**Comment by mirh** [comment]
The point was just that the documents folder isn't really meant to host game logs. 
It's not the end of the world, but you would consider a game broken if it dropped its saves there.
