### ISSUE TITLE
Console Command

### ISSUE THREAD

**Issue by heavenlyrenegade** [Erik-JS/masseffect-binkw32#3]
I use my tab key as a game key. Is there any possible way to create a version where only the tilde key enables the console instead of both?

**Comment by Mgamerz** [comment]
This is editable via Coalesced's bioinput. There is a console key entry and
a mini console entry, not sure off the top of my head. More info is
available on the me3 wiki for pc tweaks (me3).

**Comment by heavenlyrenegade** [comment]
Aha, thank you! I had an edited coalesced file but I thought this was overriding it. I've got it edited and working fine now. Thank you!

**Comment by Erik-JS** [comment]
When I saw the new email via Outlook at job, I thought this was @Mgamerz asking for a "heavenlyrenegade" console command...  :laughing: 

Anyway, I know I'm late to the party, but I'll leave here the relevant links to ME Wikia:

http://masseffect.wikia.com/wiki/PC_Tweaks
http://masseffect.wikia.com/wiki/PC_Tweaks_(Mass_Effect_2)
http://masseffect.wikia.com/wiki/PC_Tweaks_(Mass_Effect_3)

As the issue presented by @heavenlyrenegade was solved, I'm closing it now.
