### ISSUE TITLE
Error occurs when launching ME2 or ME3 after replacing binkw32.dll

### ISSUE THREAD

**Issue by pjscruggs** [Erik-JS/masseffect-binkw32#4]
This pops up after trying to launch ME2 (installed via Orgin) with this binkw32.dll in the binaries folder:

We're  sorry, an error has occurred
Invalid license. Reason code = Missing DLL: [binkw32.dll]   Error: 0x7E

**Comment by Mgamerz** [comment]
Did you check that the file exists? That error comes up when the file is
missing.

**Comment by pjscruggs** [comment]
Yes, the file existed. This happened after copying the two dll files in the "Release" folder into the ME2 binaries folder and allowing the old one to be overwritten.

**Comment by pjscruggs** [comment]
Just tried again on a fresh Orgin install of ME2. No messing with the ALOT textures or ME3 explorer. Same  issue.

**Comment by pjscruggs** [comment]
Similar error code is popping up with an Orgin installed copy of ME**3** after its binkw32.dll is replaced with the one from the ME3 "Release" folder:

We're sorry, an error has occurred
Invalid license.  Reason code = Missing DLL binkw32.dll  Error: 0x0000007e.

**Comment by Mgamerz** [comment]
Do you have the C++ redistributable installed? I think the 32bit 2012
version is required? Can't recall exact version.

**Comment by pjscruggs** [comment]
That was it. Thanks. I thought having the _latest_ version would meet that requirement.

**Comment by Mgamerz** [comment]
If anyone googles and finds this error the link to download it is https://www.microsoft.com/en-us/download/details.aspx?id=30679 and you need the 32-bit (x86)  version. It's also listed in the ME3-ASI page and this front page.
