### ISSUE TITLE
Crash on savegame load

### ISSUE THREAD

**Issue by julianxhokaxhiu** [Erik-JS/masseffect-binkw32#6]
Hi,

Two days ago I downloaded the latest version of ME3 from Origin, that I bought four years ago ( Deluxe Edition ), and I was trying to install this patch in order to get some ASI loaded. Although when I am trying to start the game, I get a `KernelBase.dll` crash.

This is the stack trace I can get from the Windows Event Collector:
```
<EventData>
  <Data>MassEffect3.exe</Data> 
  <Data>1.5.5427.124</Data> 
  <Data>50d4cab0</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.14393.321</Data> 
  <Data>57f4c291</Data> 
  <Data>e06d7363</Data> 
  <Data>000da6f2</Data> 
  <Data>24e4</Data> 
  <Data>01d249cb5e4e9c94</Data> 
  <Data>G\Origin Games\Mass Effect 3\binaries\Win32\MassEffect3.exe</Data> 
  <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data> 
  <Data>8d5b31e7-f6f9-4b09-bd8e-b0f515381af0</Data> 
  <Data /> 
  <Data /> 
  </EventData>
```

I googled already online to see if this is not related to this project, but maybe some other environment conditions: many pointed to Drivers issues, other to compatibility ( I tested Windows XP compatibility but crashes exactly in the same point ) and so on. Anyway nothing helped so far.

What I tested until now is loading my last save state ( finished 100% ) and this crash happen. While if you start a new game everything is working fine. Do you have any experience about this that can maybe help me to better understand what is happening?

I also tried to use WinDbg for debugging after crash, but it's basically the same stack-trace that you can get from Windows Log Collector. So I have no more ideas on how to go far with this.

Thank you in advance,
Julian

**Comment by Erik-JS** [comment]
So... is it related to binkw32 patch or not? Does the game load the save file without crashing while using the original binkw32.dll?

**Comment by julianxhokaxhiu** [comment]
Yes, the game loads fine without the patch.

What I discovered until now:

- NON-ORIGIN game, with the patch and my savegame files works totally fine.

- ORIGIN game, with the patch and my savegame files DOES NOT work.

- ORIGIN game WITHOUT the patch and my savegame file DOES work.

It seems that something is not being well patched on Origin? I'm not really sure. I'm still doing some more proper testing. Any idea how can I enable more verbose logging on why the crash is happening?

**Comment by julianxhokaxhiu** [comment]
Nevermind, I found the issue: the DLC I was having in the folder did not support the Italian language. If I set the game in English, then it works.

Sorry for the false alarm :)
