### ISSUE TITLE
Mass Effect 2 won't start up.

### ISSUE THREAD

**Issue by MrLagzy** [Erik-JS/masseffect-binkw32#7]
I am having problems with this DLC authenticator. I've basically tried everything, uninstalling and reinstalling all the texture mods to figure out in the end that this binkw32.dll is possibly the reason why the game won't even launch at all, nor origin giving me an error message of a .dll missing. This last try I just installed the game and copied this .dll file and the game wont even launch.

I uninstalled all the other Microsoft Visual C++ and only install the c++ 2012 update 4 which you direct to.

I was wondering if you could help out with figuring what the issue is? :)

**Comment by MrLagzy** [comment]
Dunno what I did, but it fixed itself!

**Comment by LightningCrabz** [comment]
I'm still having this issue. When I copy the 2 DLL files over, it no longer launches. 
I'm running it through Steam, not Origin, so I just get a standard "Mass Effect 2 has stopped working." error.

I was able to install the C++ 2012 update 4 which you linked. Both the x64 and the x86 ones. I'm not able to install the vcredist_arm.exe file though. When I try, it gives me an error that its not a valid Win32 application.

Let me know if there's other information I should provide. I'm new to both modding and this community.
